### ISSUE TITLE
Some strings stay untranslated

### ISSUE THREAD

**Issue by chouf1** [buddypress/bp-attachments#20]
Several strings stay untranslated in 1.1.0 beta. Tested with Twenty twelve and fifteen child themes.

Concerned area is buddymenu nav and subnav. Items are counted but text stay in english.
For ex:
`'name'            => sprintf( __( 'All <span class="%s">%s</span>', 'bp-attachments' ), esc_attr( $class ), number_format_i18n( $this->attachments_count['total'] ) ),`

**All** remains in english.

Also
Error msg stays also untranslated. Seems that comma is a blocker.
This original string
`Error while fetching the items, please try again later`
Comes up in english like
`Error while fetching the items`

*Please try again later* is not showed.

**Comment by imath** [comment]
![issue-20](https://cloud.githubusercontent.com/assets/1834524/9699567/faa9404e-53e7-11e5-80d9-1eeef7dfd6d1.png)

First was due to the fact the translation wasn't loaded soon enough, second i think it's due to the fact you added html characters in your string and strings are escaped before being printed inside the page. So using regular characters is fixing the issue. See the above screencapture.

**Comment by chouf1** [comment]
Second thought is only in because i added it deliberatly to see what happen with a html error.. If you check the first version i send to you by mail, this regular char are in. ;-)
I'm going to test and come back if i found somthing other.

Thank you very beaucoup for now !
